In [1]:
import numpy as np

In [4]:
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [5]:
a2=np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
type(a2)

numpy.ndarray

In [5]:
a2.shape

(2, 3)

In [7]:
n1.shape

(3,)

In [9]:
n1.dtype

dtype('int64')

In [10]:
n1.size ,a2.size

(3, 6)

In [11]:
import pandas as pd
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [6]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [23]:
ones=np.ones((2,3),int)

In [24]:
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [25]:
type(ones)

numpy.ndarray

In [26]:
ones.dtype

dtype('int64')

In [ ]:
zeroes=np.zeros((2,3),int,)

In [29]:
range_array=np.arange(stop=10,2)
range_array

SyntaxError: positional argument follows keyword argument (1147460682.py, line 1)

In [33]:
random_array=np.random.randint(5,size=(2,3))
random_array

array([[2, 1, 0],
       [1, 3, 2]])

In [6]:
random_array_2=np.random.random((5,3))
random_array_2

array([[0.97509113, 0.10362631, 0.39382822],
       [0.53750347, 0.91015915, 0.24800361],
       [0.61501112, 0.57565342, 0.6742774 ],
       [0.73916912, 0.73262058, 0.28008265],
       [0.83884639, 0.91739169, 0.87857264]])

In [7]:
random_array_3=np.random.rand(5,3)
random_array_3

array([[0.63186476, 0.52553116, 0.33353045],
       [0.35580198, 0.21567637, 0.41883838],
       [0.58281238, 0.03949595, 0.9351878 ],
       [0.10138709, 0.58944754, 0.94980841],
       [0.73959544, 0.41838985, 0.31038381]])

In [11]:
np.random.seed(seed=0)
random_array_4=np.random.randint(5,size=(5,3))
random_array_4

array([[4, 0, 3],
       [3, 3, 1],
       [3, 2, 4],
       [0, 0, 4],
       [2, 1, 0]])

In [12]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4])

In [13]:
n1

NameError: name 'n1' is not defined

In [2]:
a1

NameError: name 'a1' is not defined

In [ ]:
a2

In [3]:
a3

NameError: name 'a3' is not defined

In [21]:
a1[0]

1

In [28]:
a2[1,2]

6

In [32]:
a3[1,1,2]

12

In [34]:
a3.shape

(3, 2, 3)

In [38]:
a3[1,0,1]

8

**Manipulating and comparing arrays**